apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: httpecho
  name: httpecho
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: httpecho
    spec:
      containers:
      - image: httpecho:0.1
        name: httpecho
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: httpecho
  name: httpecho
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: httpecho
